// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRrC8EpXm2DBe2lOXR8bDbiafMvqQ4oHk',
    appId: '1:460953816961:web:7369cbb548ce264e4d2280',
    messagingSenderId: '460953816961',
    projectId: 'e-event-app',
    authDomain: 'e-event-app.firebaseapp.com',
    storageBucket: 'e-event-app.appspot.com',
    measurementId: 'G-HMZ17J8KQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5VwjvGWMlnlxRo7UlAhIdiKHaqdBMSF4',
    appId: '1:460953816961:android:af81c0a77f2591da4d2280',
    messagingSenderId: '460953816961',
    projectId: 'e-event-app',
    storageBucket: 'e-event-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5z-HLYAMLaaaJRgH_z0hfgZT6A60bXAM',
    appId: '1:460953816961:ios:d2aafe37ae9067974d2280',
    messagingSenderId: '460953816961',
    projectId: 'e-event-app',
    storageBucket: 'e-event-app.appspot.com',
    iosClientId: '460953816961-50i5qevapckt75eqp9mqcg1fea6ut35p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eVent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5z-HLYAMLaaaJRgH_z0hfgZT6A60bXAM',
    appId: '1:460953816961:ios:d2aafe37ae9067974d2280',
    messagingSenderId: '460953816961',
    projectId: 'e-event-app',
    storageBucket: 'e-event-app.appspot.com',
    iosClientId: '460953816961-50i5qevapckt75eqp9mqcg1fea6ut35p.apps.googleusercontent.com',
    iosBundleId: 'com.example.eVent',
  );
}
